# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171108_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='api',
            name='choices',
        ),
    ]
