# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20171108_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='branch',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
