# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_api_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='notice_author',
        ),
    ]
