# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_api_notice_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='notice_author',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
