# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20171109_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='notice_author',
            field=models.CharField(default='admin', max_length=20),
        ),
    ]
