# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 04:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0016_auto_20171111_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='api',
            name='notice_file',
            field=models.FileField(blank=True, null=True, upload_to='accounts/notcie_files/'),
        ),
    ]
