# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20171111_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='notice_file',
            field=models.FileField(blank=True, null=True, upload_to='accounts/notice_files/'),
        ),
    ]
