# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20171124_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='notice_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
